//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THI_Analysis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBERSOURCESYSTEM
    {
        public int MEMBERSOURCESYSTEMKEY { get; set; }
        public Nullable<int> PROJECTKEY { get; set; }
        public string DATASET { get; set; }
        public string SOURCESYSTEM { get; set; }
    
        public virtual SalesforceProject SalesforceProject { get; set; }
    }
}
