//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberProfiling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppModulesInfo
    {
        public int AppModuleInfoKey { get; set; }
        public int MemberProfileKey { get; set; }
        public int AppModuleKey { get; set; }
        public bool Problem_Module__Services_ { get; set; }
        public bool Problem_Modules__Defects_ { get; set; }
        public bool Modules_Accessed { get; set; }
    
        public virtual AppModule AppModule { get; set; }
        public virtual MemberProfilingMaster MemberProfilingMaster { get; set; }
    }
}
