//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberProfiling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberProfilingMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MemberProfilingMaster()
        {
            this.AppModulesInfoes = new HashSet<AppModulesInfo>();
        }
    
        public int MemberProfileKey { get; set; }
        public System.DateTime Record_Dt { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public int Project { get; set; }
        public string Brief_history_of_Member { get; set; }
        public Nullable<int> Data_Validation___Accuracy_Issues { get; set; }
        public Nullable<int> Data_Load___Implementation_Timeliness { get; set; }
        public Nullable<int> Relationship_Strength { get; set; }
        public string Services_Current_Issues { get; set; }
        public string Services_Current_Resolution_Plan { get; set; }
        public Nullable<int> Open_Enhancements___Defects { get; set; }
        public Nullable<int> Engagement { get; set; }
        public string PD_Current_Issues { get; set; }
        public string PD_Current_Resolution_Plan { get; set; }
        public bool IsUpdated { get; set; }
        public string Overall_Comments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppModulesInfo> AppModulesInfoes { get; set; }
        public virtual ProfilingScore ProfilingScore { get; set; }
        public virtual ProfilingScore ProfilingScore1 { get; set; }
        public virtual ProfilingScore ProfilingScore2 { get; set; }
        public virtual ProfilingScore ProfilingScore3 { get; set; }
        public virtual SalesforceProject SalesforceProject { get; set; }
        public virtual ProfilingScore ProfilingScore4 { get; set; }
    }
}
