//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberProfiling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfilingScore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProfilingScore()
        {
            this.MemberProfilingMasters = new HashSet<MemberProfilingMaster>();
            this.MemberProfilingMasters1 = new HashSet<MemberProfilingMaster>();
            this.MemberProfilingMasters2 = new HashSet<MemberProfilingMaster>();
            this.MemberProfilingMasters3 = new HashSet<MemberProfilingMaster>();
            this.MemberProfilingMasters4 = new HashSet<MemberProfilingMaster>();
        }
    
        public int ProfileScoreKey { get; set; }
        public int Score { get; set; }
        public string ScoreDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberProfilingMaster> MemberProfilingMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberProfilingMaster> MemberProfilingMasters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberProfilingMaster> MemberProfilingMasters2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberProfilingMaster> MemberProfilingMasters3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberProfilingMaster> MemberProfilingMasters4 { get; set; }
    }
}
