//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberProfiling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectView
    {
        public int ProjectKey { get; set; }
        public string ProjectName { get; set; }
        public string ProjectPhase { get; set; }
        public Nullable<int> Days_to_Contract_Decision { get; set; }
        public string BusinessAnalyst { get; set; }
        public string DataAnalyst { get; set; }
        public string DedicatedAdvisor { get; set; }
        public Nullable<double> AnnualContractValue { get; set; }
        public Nullable<System.DateTime> EarliestContractStartDate { get; set; }
        public Nullable<System.DateTime> NextContractDecision { get; set; }
        public Nullable<System.DateTime> LatestContractEndDate { get; set; }
    }
}
